default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: offers_development

test:
  <<: *default
  database: offers_test

production:
  <<: *default
  database: <%= ENV['AWS_DATABASE_URL'] %>
